import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer";
import Testimonials from "@/components/Testimonials";
import TaxFile from "@/components/TaxFile";
import Service from "@/components/service";
import Team from "@/components/Team";
import TestimonialsCard2 from "@/card/Home2/TestimonialsCard2";
import Testimonials2 from "@/components/home2/Testimonials2";


export const metadata = {
  title: "TaxStick",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Testimonials2/>
        {/* <Team/> */}
        {/* <Service/> */}
        {/* <TaxFile/> */}
        {/* <Testimonials/> */}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
